Issue 5
taichi-kobaya/wordpress_tutorial pull request #7
Opened 2021-04-18 03:03 UTC by taichi-kobaya

SCSS導入しました。確認お願いします。

2021-04-18 03:25 UTC, taichi-kobaya commented
もう一点変更がありましたので、変更し直してプッシュしました。

2021-04-18 04:17 UTC, Takuma-Ikeda commented
@taichi-kobaya @katakabe 
#4 でもコメントしましたが `.gitignore` を導入しましょうか
Node.js のライブラリだけで 5000 件以上のファイルがコミットに含まれています。
`.gitignore` を使って `node_modules` 配下のものはコミットできないようにしてください。

2021-04-18 04:22 UTC, Takuma-Ikeda commented
GitHub に管理するのは `package.json` だけで十分です。
これさえあれば `yarn install` とか `npm install` するだけでライブラリを取得できるからです。

ライブラリ本体が入っている `node_modules` は重たくなるだけなので不要、にするのが一般的です。
※ `node_modules` は削除して問題ありません。いつでもインストールし直せるので。

2021-04-18 04:25 UTC, Takuma-Ikeda commented
@taichi-kobaya
Assignee を設定してください！

2021-04-18 04:40 UTC, Takuma-Ikeda commented
念の為、動作確認もお願いします
※ 対象のフォルダにちゃんと css ファイルが吐き出されたかどうか
README.md にも使用した Node.js のバージョンなど記載しておいてください

2021-04-18 08:26 UTC, Takuma-Ikeda requested changes
`wordpress/wp-content/themes/xeory_extension-child/style.css` 
これ不要です！これなくても親テーマの `style.css` を参照しますし、
`scss` から吐き出された `css` を使うべきだからです。

2021-04-18 08:26 UTC, Takuma-Ikeda commented on wordpress/gulpfile.js
> +exports.default = watchScss;
ファイルの最終行は空行にするのがベターと言われています。

2021-04-18 21:44 UTC, Takuma-Ikeda requested changes

2021-04-18 21:44 UTC, Takuma-Ikeda commented on .gitignore
> +/wordpress/wp-content/.DS_Store
個別に 3 つも指定する必要はないはずです
こういう指定の仕方だと `.DS_Store` が出てくるたびに `.gitignore` に追記をしなくてはなりません

2021-04-19 04:14 UTC, Takuma-Ikeda requested changes
`wordpress/.DS_Store` が消えておりません。

2021-04-19 04:14 UTC, Takuma-Ikeda commented on .vscode/settings.json
> +}
@taichi-kobaya 
`settings.json` が除外されておりません。ご確認よろしくお願いします。

2021-04-19 04:15 UTC, Takuma-Ikeda commented
@taichi-kobaya 
対応したものについては僕のコメントに返信してください！

2021-04-19 04:19 UTC, Takuma-Ikeda requested changes

2021-04-19 04:19 UTC, Takuma-Ikeda commented on wordpress/src/scss/sample.scss
> +}
最終行は空行にしましょう

2021-04-19 04:19 UTC, Takuma-Ikeda commented on wordpress/src/scss/style.scss
> +*/
最終行は空行にしましょう

2021-04-19 04:20 UTC, Takuma-Ikeda commented on .gitignore
> +/wordpress/wp-content/.DS_Store
こちらの修正確認しました。

2021-04-19 04:22 UTC, Takuma-Ikeda commented
Gulp の使い方も `README.md` に記載しましょうか

2021-04-19 09:02 UTC, Takuma-Ikeda commented
@taichi-kobaya 
`wordpress/wp-includes` 配下のファイルが全部削除されており、
とんでもない数のファイルが修正されていますがどういうことですか？
![スクリーンショット 2021-04-19 18 01 50](https://user-images.githubusercontent.com/27577954/115210223-5c60fd00-a139-11eb-9118-d87b6abf2e74.png)

2021-04-19 10:07 UTC, taichi-kobaya commented
> Gulp の使い方も `README.md` に記載しましょうか

mainブランチのREADME.md に記載しました。

2021-04-19 10:08 UTC, Takuma-Ikeda commented
LGTM です！

2021-04-19 10:08 UTC, merged